//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTB.Authentication.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppDatabaseRole
    {
        public int adbID { get; set; }
        public Nullable<int> appID { get; set; }
        public string adbName { get; set; }
        public string adbRoleName { get; set; }
        public string adbAccessKey { get; set; }
        public bool adbActive { get; set; }
        public string adbCreatedBy { get; set; }
        public System.DateTime adbCreatedDate { get; set; }
        public string adbModifiedBy { get; set; }
        public System.DateTime adbModifiedDate { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
