//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTB.Authentication.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Application()
        {
            this.AppDatabaseRoles = new HashSet<AppDatabaseRole>();
            this.AppUsers = new HashSet<AppUser>();
        }
    
        public int appID { get; set; }
        public string appName { get; set; }
        public Nullable<int> appFlags { get; set; }
        public bool appActive { get; set; }
        public string appCreatedBy { get; set; }
        public System.DateTime appCreatedDate { get; set; }
        public string appModifiedBy { get; set; }
        public System.DateTime appModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppDatabaseRole> AppDatabaseRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppUser> AppUsers { get; set; }
    }
}
