//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTB.Authentication.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUserSetting
    {
        public int setID { get; set; }
        public Nullable<int> apuID { get; set; }
        public string setName { get; set; }
        public string setValue { get; set; }
        public Nullable<int> setContentTypeID { get; set; }
        public bool setActive { get; set; }
        public string setCreatedBy { get; set; }
        public Nullable<System.DateTime> setCreatedDate { get; set; }
        public string setModifiedBy { get; set; }
        public System.DateTime setModifiedDate { get; set; }
    
        public virtual ContentType ContentType { get; set; }
        public virtual AppUser AppUser { get; set; }
    }
}
