//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTB.Authentication.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppUser()
        {
            this.AppUserSettings = new HashSet<AppUserSetting>();
        }
    
        public int apuID { get; set; }
        public int appID { get; set; }
        public int usrID { get; set; }
        public bool apuActive { get; set; }
        public byte[] apuAccessKey { get; set; }
        public string apuCreatedBy { get; set; }
        public System.DateTime apuCreatedDate { get; set; }
        public string apuModifiedBy { get; set; }
        public System.DateTime apuModifiedDate { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppUserSetting> AppUserSettings { get; set; }
    }
}
