//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTB.Authentication.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.AppUsers = new HashSet<AppUser>();
        }
    
        public int usrID { get; set; }
        public string usrLogin { get; set; }
        public string usrLastName { get; set; }
        public string usrFirstName { get; set; }
        public string usrClock { get; set; }
        public string usrEmail { get; set; }
        public bool usrActive { get; set; }
        public string usrCreatedBy { get; set; }
        public System.DateTime usrCreatedDate { get; set; }
        public string usrModifiedBy { get; set; }
        public System.DateTime usrModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppUser> AppUsers { get; set; }
    }
}
